function [real_node_boundary,real_node_inside,real_node_useful,real_node_not_useful] = find_inside_and_boundary_node_index(...
                                Nx_big,Ny_big,Nnode_big,...
                                Nx_small,Ny_small,Nnode_small,...
                                left_pos_at_big,right_pos_at_big,forward_pos_at_big,backward_pos_at_big,ratio)
%% find big node useful
    [real_big_node_boundary,real_big_node_inside,real_big_node_useful,real_big_node_not_useful]= ...
                                           find_big_node_useful(Nx_big,Ny_big,...
                                                  left_pos_at_big,right_pos_at_big,forward_pos_at_big,backward_pos_at_big);
%% find small node useful
    [real_small_node_boundary,real_small_node_inside,real_small_node_useful,real_small_node_not_useful]= ...
                              find_small_node_useful(Nx_small,Ny_small,Nnode_big,...
                                     left_pos_at_big,right_pos_at_big,forward_pos_at_big,backward_pos_at_big,ratio);
%% add up
    real_node_boundary = [real_big_node_boundary;real_small_node_boundary];
    real_node_inside = [real_big_node_inside;real_small_node_inside];
    real_node_useful = [real_big_node_useful;real_small_node_useful];
    real_node_not_useful = [real_big_node_not_useful;real_small_node_not_useful];
end